### **TUGAS 2**
### **MATRIKS**

### Pengertian Matriks
Matriks merupakan susunan bilangan real yang dapat diidentifikasi baris dan kolom nya yang ditempatkan didalam kurung siku, matriks dapat dinotasikan dengan huruf kapital seperti A,B, dan seterusnya. Didalam matriks terdapat elemen-elemen matriks yang dinotasikan dengan huruf kecil yang setiap elemen memiliki baris dan kolom yang berbeda, seperti $a_{ij}=$ a elemen, i baris, j kolom. contoh: $a_{12}$ artinya elemen a terletak dibaris 1 dan kolom ke 2.  

* Ukuran matriks ditentukan oleh jumlah baris dan kolom.  
contoh : Matriks A berukuran 3x3 (3 baris 3 kolom)
$
A=\begin{bmatrix}
2 & 4 & 5\\
4 & 6 & 9
\end{bmatrix}
$


### Jenis-jenis matriks:
1. Matriks nol, matriks yang semua elemen
penyusunnnya nol.
2. Matriks baris, matriks yang elemennya hanya satu baris.
3. Matriks kolom, matriks yang elemennya hanya satu kolom.
4. Matriks persegi adalah matriks yang mempunyai jumlah baris dan kolom yang sama.
5. Matriks diagonal,matriks persegi yang semua elemen di luar diagonal utamanya bernilai nol.
6. Matriks skalar, matriks yang elemen pada diagonal utamanya sama dan elemen diluar diagonal bernilai nol.
7. Matriks identitas, matriks skalar yang elemen pada diagonal utamanya sama dengan satu.
8. Matriks simetri, matriks persegi yang sama dengan transpose matriks itu sendiri.
9. Matriks simetri miring, matriks persegi yang sama dengan negatif matriks transposnya
10. Matriks segitiga atas, matriks persegi yang elemen-elemen di bawah diagonal utamanya adalah nol.
11. Matriks segitiga bawah, matriks persegi yang elem-elemen di atas diagonal utamanya adalah nol.
12. Matriks tranpose, matriks yang mengubah elemen di baris menjadi kolom. 

### Implementasi Matriks dengan Numpy  


In [1]:
import numpy as np
A = np.array([[1,3,6],[2,1,5],[4,2,1]])
B = np.array([[3,1,6],[5,5,3],[5,8,9]])
C = np.array([[4,5],[5,0],[7,8]])
D = np.array([[3,3,6],[5,7,3],[5,8,8]])

print("A=\n",A)
print("B=\n",B)
print("C=\n",C)
print("D=\n",D)
print("\n")
print("Ukuran matriks :",A.shape) #ukuran matriks
print("Jumlah baris :", A.shape[0])# jumlah baris
print("Jumlah kolom :", A.shape[1])# jumlah kolom

A=
 [[1 3 6]
 [2 1 5]
 [4 2 1]]
B=
 [[3 1 6]
 [5 5 3]
 [5 8 9]]
C=
 [[4 5]
 [5 0]
 [7 8]]
D=
 [[3 3 6]
 [5 7 3]
 [5 8 8]]


Ukuran matriks : (3, 3)
Jumlah baris : 3
Jumlah kolom : 3


Dengan metode *Shape* kita dapat mengakses ukuran matriks, berdasarkan jumlah baris dan kolom dalam array. Contoh: Matriks A memilki ukuran 3x3 dengan rincian 3 baris dan 3 kolom.

In [2]:
y = np.random.randint(5,size=(3,3)) # menampilkan angka random dengan rentang 0-5 dengan ukuran matriks 3x3
print(y)

[[1 1 4]
 [2 4 4]
 [2 0 3]]


### Operasi pada Matriks
Operasi matriks adalah serangkaian operasi atau tindakan yang dilakukan pada matriks, baik itu untuk mengubah matriks ataupun menggabungkan matriks. Berikut beberapa operasi matriks yang sering digunakan:

In [3]:
import numpy as np
import sympy as sy

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])
c=np.array([[3,4],[-2,4],[2,5]])
print('A=\n',a)
print('B=\n',b)
print('C=\n',c)

A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
B=
 [[ 2  4  7]
 [ 6 -3  2]
 [ 5 -2  7]]
C=
 [[ 3  4]
 [-2  4]
 [ 2  5]]


### 1.Penjumlahan matriks :

Operasi ini melibatkan penambahan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENJUMLAHAN MATRIKS A + B :

\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}\\
A + B =
\begin{bmatrix}
2+2&3+4&2+7\\
4+6&1+(-3)&-3+2\\
-1+5&-2+(-2)&2+7
\end{bmatrix}
=
\begin{bmatrix}
4&7&9\\
10&-2&-1\\
4&-4&9
\end{bmatrix}
\end{align*}


BERIKUT PROGRAM UNTUK PENJUMLAHAN MATRIKS:

In [4]:
print('A+B=\n',a+b)
print('B+A=\n',b+a)
print('Sifat di atas merupakan sifat komutatif karena A+B = B+A')

A+B=
 [[ 4  7  9]
 [10 -2 -1]
 [ 4 -4  9]]
B+A=
 [[ 4  7  9]
 [10 -2 -1]
 [ 4 -4  9]]
Sifat di atas merupakan sifat komutatif karena A+B = B+A


### 2.Pengurangan Matriks:

Operasi ini melibatkan pengurangan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENGURANGAN MATRIKS:

\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}\\
A - B =
\begin{bmatrix}
2-2&3-4&2-7\\
4-6&1-(-3)&-3-2\\
-1-5&-2-(-2)&2-7
\end{bmatrix}
=
\begin{bmatrix}
0&-1&-5\\
-2&4&-5\\
-6&-0&-5
\end{bmatrix}
\end{align*}

BERIKUT PROGRAM UNTUK PENGURANGAN MATRIKS:

In [5]:
print('A-B=\n',a-b)
print('B-A=\n',b-a)
print('Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A')

A-B=
 [[ 0 -1 -5]
 [-2  4 -5]
 [-6  0 -5]]
B-A=
 [[ 0  1  5]
 [ 2 -4  5]
 [ 6  0  5]]
Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A


### 3.Perkalian Matriks:

Operasi ini melibatkan perkalian elemen-elemen matriks. Untuk melakukan perkalian matriks A dan B, jumlah kolom dalam matriks A harus sama dengan jumlah baris dalam matriks B. Contoh matriks A memiliki ordo atau ukuran mxn, maka matriks B harus memiliki ordo atau ukuran nxp. Sehingga hasil dari perkalian tersebut akan menghasilkan matriks baru dengan ukuran mxp. Hasilnya akan memiliki jumlah baris yang sama dengan matriks A dan jumlah kolom yang sama dengan matriks B.

CONTOH PERKALIAN MATRIKS:


\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}\\
A X B =
\begin{bmatrix}
2(2)+3(6)+2(5) &2(4)+3(-3)+2(-2)&2(7)+3(2)+2(7)\\
4(2)+1(6)+(-3)(5) &4(4)+1(-3)+(-3)(-2) &4(7)+1(2)+(-3)(7)\\
-1(2)+(-2)(6)+2(5) &-1(4)+(-2)(-3)+2(-2) &-1(7)+(-2)(2)+2(7)
\end{bmatrix}
=
\begin{bmatrix}
32&-5&34\\
-1&19&9\\
-4&-2&3
\end{bmatrix}
\end{align*}

BERIKUT PROGRAM UNTUK PERKALIAN MATRIKS:

In [6]:
print('AB=\n',a@b)
print('AC=\n',a@c)
print('BC=\n',b@c)

AB=
 [[32 -5 34]
 [-1 19  9]
 [-4 -2  3]]
AC=
 [[ 4 30]
 [ 4  5]
 [ 5 -2]]
BC=
 [[12 59]
 [28 22]
 [33 47]]


- Sifat Asosiasi:

  (AB)C = A(BC)

In [7]:
print('A(BC) =\n', a@(b@c))
print('(AB)C =\n',(a@b)@c)

A(BC) =
 [[174 278]
 [-23 117]
 [ -2  -9]]
(AB)C =
 [[174 278]
 [-23 117]
 [ -2  -9]]


- Perkalian skalar:

  c(AB) = (cA)B = A(cB)

In [8]:
c = 3
print('c(AB)\n',c*(a@b))
print('(cA)B\n',(c*a)@b)
print('A(cB)\n',a@(c*b))

c(AB)
 [[ 96 -15 102]
 [ -3  57  27]
 [-12  -6   9]]
(cA)B
 [[ 96 -15 102]
 [ -3  57  27]
 [-12  -6   9]]
A(cB)
 [[ 96 -15 102]
 [ -3  57  27]
 [-12  -6   9]]


- Perkalian identitas:

  AI = IA = A

In [9]:
i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


- Tidak berlaku sifat kumutatif:

  AB != BA atau AB tidak sama dengan BA

In [10]:
print('AB=\n',a@b)
print('BA=\n',b@a)

AB=
 [[32 -5 34]
 [-1 19  9]
 [-4 -2  3]]
BA=
 [[13 -4  6]
 [-2 11 25]
 [-5 -1 30]]


### 4.Transpose Matriks

Transpose matriks adalah matriks baru yang diperoleh dengan cara menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya. Jika sebuah matriks berukuran M X N, maka transpose matriks tersebut memiliki ordo N X M.

CONTOH TRANSPOSE MATRIKS:

\begin{align*}
C=
\begin{bmatrix}
3&4\\
-2&4\\
2&5
\end{bmatrix}
&&
CT (C Transposre)=
\begin{bmatrix}
3&-2&2\\
4&4&-5
\end{bmatrix}
\end{align*}

BERIKUT PROGRAM UNTUK MENG-TRANSPOSE MATRIKS:

In [11]:
c=np.array([[3,4],[-2,4],[2,5]])
c_tran = c.transpose()
print('matrik c sebelum di transpose=\n', c)
print('matrik c setelah di transpose=\n',c_tran)
print('ordo C_transpose adalah',c_tran.shape)
z=c_tran@c
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=c@c_tran
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)
print("Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose")

matrik c sebelum di transpose=
 [[ 3  4]
 [-2  4]
 [ 2  5]]
matrik c setelah di transpose=
 [[ 3 -2  2]
 [ 4  4  5]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[17 14]
 [14 57]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[25 10 26]
 [10 20 16]
 [26 16 29]]
ordo P adalah (3, 3)
Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose


### Program untuk Mengalikan Matriks

In [12]:
def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)

#JIKA USER INGIN MENGINPUTKAN MATRIKSNYA SENDIRI BISA MENGGUNAKAN CODE DIBAWAH INI :
"""def input_matrix():
    baris = int(input("Masukkan jumlah baris: "))
    kolom = int(input("Masukkan jumlah kolom: "))
    matrix = []
    for i in range(baris):
        row = []
        print(f"Masukkan elemen untuk baris {i + 1}: ")
        for j in range(kolom):
            element = float(input(f"Elemen [{i + 1}, {j + 1}]: "))
            row.append(element)
        matrix.append(row)
    return matrix

print("Program perkalian matriks!!")
print("Masukkan matriks pertama:")
matriks1 = input_matrix()
print ("Matriks 1 = ", matriks1)
print("Masukkan matriks kedua:")
matriks2 = input_matrix()
print ("Matriks 2 = ",matriks2)
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)"""


print ("Berikut adalah contoh matriks")
print ("""
matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])
""")
matriks1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks2=([[2,4,7],[6,-3,2],[5,-2,7]])
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)


Berikut adalah contoh matriks

matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])


Hasil perkalian matriks:
[32, -5, 34]
[-1, 19, 9]
[-4, -2, 3]


BERIKUT PENJELASAN MENGENAI CODINGAN DI ATAS:

1. Fungsi perkalian :
  - def perkalian(matrix1, matrix2):
    
     - sebuah fungsi bernama 'perkalian' yang memiliki dua parameter yaitu matrix1 dan matrix2.

  - if len(matrix1[0]) != len(matrix2):

        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        
        return None
      - pengujian awal untuk memastikan bahwa matriks dapat dikalikan. Jika jumlah kolom dalam matrix1 tidak sama dengan jumlah baris dalam matrix2, maka perkalian matriks tidak bisa dilakukan. Dalam hal ini, fungsi akan mencetak pesan kesalahan dan mengembalikan None.
